apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: vllm-from-semantic-router
  namespace: vllm
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: semantic-router
  to:
    - group: ""
      kind: Service
      name: vllm-qwen-instruct-engine-service
