apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: semantic-router
  namespace: semantic-router
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: semantic-router-api
  extProc:
    - backendRefs:
        - group: ""
          kind: Service
          name: semantic-router
          port: 50051
      failOpen: false
      messageTimeout: 60s
      processingMode:
        allowModeOverride: true
        request:
          body: Buffered
        response:
          body: Buffered
