apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: semantic-router
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/vllm-project/charts/semantic-router
  ref:
    tag: "0.3.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
