apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - inference
  - semantic-router
labels:
  - pairs:
      app.kubernetes.io/part-of: ai-platform
    includeSelectors: false
